# Generated by Django 5.2.7 on 2025-11-06 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontainer', '0036_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmobile',
            name='mainmtodaydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
